### PR TITLE
Front end for Donation page

### PR DESCRIPTION
**Pull request by GameGodS3**
Only left side text and lower menu have been made
Alignment for the box on right side has been made with css. Add a div element of the said box for filling.
Heart icon and donate button have been included.

### CODE REVIEW

**Review by abhijithneilabraham — COMMENTED** [review]
Complete the frontend with the rest too.

**Review by gksoriginals — CHANGES_REQUESTED** [review]
Please create a separate branch and push to there. Please don't push to master.

**Comment by gksoriginals** [comment]
@abhijithneilabraham you have access to create a separate branch for @GameGodS3 in the TinkerHub repo.

**Comment by gksoriginals** [comment]
Screenshot 2020-04-11 at 6 03 42 PM
@GameGodS3 could you make the contents a bit to the center ? Looks like extra space in the bottom.

**Pull request closed without merging**
